### PR TITLE
Fix for #89

### PR DESCRIPTION
**Pull request by pietermees**
Fix for "Invalid startup packet layout: expected terminator as last byte"

### CODE REVIEW

**Review by DMickens — APPROVED** [review]
Approving as, at the very least, a short term fix. Making note to verify in protocol documentation

**Comment by sitingren** [comment]
@DMickens CI test regression is introduced from this PR.

**Comment by DMickens** [comment]
@sitingren Reverting and investigating. 

Not sure why CI tests weren't ran automatically and caught in the PR, will look into that as well

**Comment by pietermees** [comment]
This change worked for me in my use case and was recommended on the original issue #89
I'm not sure why the test suite would not have run though.

**Pull request merged**
