### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by DMickens**
Removal of all past node-postgres version change information, and note that we are in prerelease with version 0.9.0. No details added as this is the first release.

### CODE REVIEW

**Comment by jeremyprime** [comment]
Should we include the initial differences between node-postgres and vertica-nodejs in this document (or another document in this repo), or should we keep that list of changes on the internal wiki for now?

**Comment by sitingren** [comment]
We can just remove this file and track changes in https://github.com/vertica/vertica-nodejs/releases Github release note. See [python client](https://github.com/vertica/vertica-python/releases) for example.

From https://zellwk.com/blog/publish-to-npm/:
> This means publishing a package involves many steps. At the very least, you need to:
 1.Run tests (if there are any)
2.Update version in package.json according to Semver
3.Create a git tag according to Semver
4.Push the package to Github
5.Push the package to npm
6.Create release notes for every update

**Comment by DMickens** [comment]
> Should we include the initial differences between node-postgres and vertica-nodejs in this document (or another document in this repo), or should we keep that list of changes on the internal wiki for now?

I would say no. This isn't intended to be a next step from node-postgres, this is just our first release. There is no baseline, the differences that we describe would just be vertica-specific changes for the most part which instead is just whats going to be described in the usage/readme, etc.

**Comment by DMickens** [comment]
> We can just remove this file and track changes in https://github.com/vertica/vertica-nodejs/releases Github release note. See [python client](https://github.com/vertica/vertica-python/releases) for example.
> 
> From https://zellwk.com/blog/publish-to-npm/:
> 
> > This means publishing a package involves many steps. At the very least, you need to:
> > 1.Run tests (if there are any)
> > 2.Update version in package.json according to Semver
> > 3.Create a git tag according to Semver
> > 4.Push the package to Github
> > 5.Push the package to npm
> > 6.Create release notes for every update

I think that is the right thing to do. I've deleted this file instead of modifying it. We'll use github releases moving forward.

**Review by jeremyprime — APPROVED** [review]

**Pull request merged**
