### PR TITLE
Update package versions to 0.9.0-pre.6

### PR DESCRIPTION
**Pull request by jonathanl-bq**
This PR updates the package versions to 0.9.0-pre.6 in preparation for our next release. We should not publish the next release until #28 and #27 have been merged.

### CODE REVIEW

**Review by alexr-bq — APPROVED** [review]

**Comment by sitingren** [comment]
I know this client is still in early stage. I'd like to know what's the plan for creating releases in https://github.com/vertica/vertica-nodejs/releases?

**Comment by williammatherjones** [comment]
> I know this client is still in early stage. I'd like to know what's the plan for creating releases in https://github.com/vertica/vertica-nodejs/releases?

For node.js open source, releases are done by publishing to the npm.   While it would certainly make sense for a release to be required for this process, npm publishing is done directly from the source code.    For example, if you look at node-postgres, you will see that there are no releases.  I don't think it makes sense to create releases for node based drivers because packages are installed using npm.

**Review by williammatherjones — APPROVED** [review]

**Comment by jeremyprime** [comment]
> > I know this client is still in early stage. I'd like to know what's the plan for creating releases in https://github.com/vertica/vertica-nodejs/releases?
> 
> For node.js open source, releases are done by publishing to the npm. While it would certainly make sense for a release to be required for this process, npm publishing is done directly from the source code. For example, if you look at node-postgres, you will see that there are no releases. I don't think it makes sense to create releases for node based drivers because packages are installed using npm.

Would still be nice to have releases to track what has changed, at least once we get to version 1.0.0.  Otherwise we should bring back the CHANGELOG.md at that point.

**Comment by williammatherjones** [comment]
> Would still be nice to have releases to track what has changed, at least once we get to version 1.0.0. Otherwise we should bring back the CHANGELOG.md at that point.

Sure.  I'm fine with anything we think makes it easier for people to find and track versions of the driver.

**Pull request merged**
