### PR TITLE
Finalized package keywords

### PR DESCRIPTION
**Pull request by williammatherjones**
Added a bunch of keywords that are specific to Vertica to get ready for the publish to npm we will be doing later today.

### CODE REVIEW

**Comment by jeremyprime** [comment]
Should we add keywords to the v-protocol package (right now it does not have any)?

**Comment by williammatherjones** [comment]
I was assuming v-protocol should not have keywords because it does not implement an API.  It is used by the other packages.

**Comment by jeremyprime** [comment]
I figure there should be at least a couple terms that would allow a user to find all the packages related to this project, even if they don't intend to use it directly (e.g. "vertica" and "vertica-nodejs" could be keywords for all modules).

I can't find an example right now to see how other projects with multiple modules make use of keywords.

**Review by alexr-bq — APPROVED** [review]

**Review by jonathanl-bq — APPROVED** [review]
If we're certain that we don't want v-protocol to have any keywords, then I think this is fine to merge now.

**Pull request merged**
